
SET SERVEROUTPUT ON

-- Criando a Tabela Salario
CREATE TABLE SALARIO(
    ID NUMBER PRIMARY KEY,
    SALARIO_ATUAL NUMBER(10, 2),
    SALARIO_NOVO NUMBER(10, 2)
);

-- Testando o PL/SQL
DECLARE
 V_SAL_ATUAL NUMBER(10,2) := 1212.00;
 V_SAL_REAJ NUMBER (10,2);
BEGIN
    V_SAL_REAJ := V_SAL_ATUAL * 1.25;
    DBMS_OUTPUT.put_line('SALÁRIO ATUAL - R$:' || V_SAL_ATUAL);
    DBMS_OUTPUT.put_line('SALÁRIO REAJUSTADO - R$:' || V_SAL_REAJ);
END;

-------

-- Fazendo insert com Loop
DECLARE
 V_ATU NUMBER;
 V_ID NUMBER := 1;
 
BEGIN
 FOR X IN 1..10 LOOP
 INSERT INTO SALARIO(ID, SALARIO_ATUAL, SALARIO_NOVO) VALUES (V_ID, 
 DBMS_RANDOM.VALUE(1300, 15000), DBMS_RANDOM.VALUE(1300, 15000));
 V_ID := V_ID + 1;
 END LOOP;
 COMMIT;
END;

-------

-- Alterando o Salario Novo aumentando 25% do salario atual
DECLARE
 V_ATU NUMBER;
 V_REAJ NUMBER;
BEGIN
 FOR X IN 1..10 LOOP
 
SELECT SALARIO_ATUAL INTO V_ATU FROM SALARIO WHERE ID = X;
--DBMS_OUTPUT.put_line(V_ATU);
 V_REAJ := V_ATU * 1.25;
 UPDATE SALARIO SET SALARIO_NOVO = V_REAJ WHERE ID = X;
 
 END LOOP;
 COMMIT;
END;

SELECT * FROM SALARIO; 